### ISSUE TITLE
How to use pretrained model

### ISSUE THREAD

**Issue by Muller-Liu** [JinZhuXing/Fingerprint_TF#1] opened 2020-04-10 16:34 UTC
Hi, I want to use the pretrained model derectly to train model. But after I changed the checkpoint folder and ran the 02_01.py, I got such error：Shapes (64,) and (32,) are incompatible， which comes from "model.load_weights(checkpoint_path)". I searched a lot but still confused. Please help me!!! Thank you!

**Comment by JinZhuXing** [comment] 2020-04-11 01:25
@Muller-Liu Thank you for your interest in my project.
Pretrained model is trained with master branch network.
In this project, there are two branches.
Main branch is master and the other is new model network brunch.
Please checkout repo as master brunch and test it.
Thank you.

**Comment by Ehtasha** [comment] 2020-09-08 11:56
@Muller-Liu  Have you resolve this issue ?

@JinZhuXing  I'm using master branch but still facing same error. 

Any other suggestion or alternative to use pre-trained model ?

**Error Statement:**  ValueError: Shapes (64,) and (32,) are incompatible

**Comment by Ehtasha** [comment] 2020-09-11 13:41
@Muller-Liu 
After placing checkpoint files make sure to create folder with the name 'result' within model folder.
This will resolve above issue

**Comment by JinZhuXing** [comment] 2020-09-11 13:46
Thank you.
Now, may we close this issue?

**Comment by Ehtasha** [comment] 2020-09-11 13:49
@JinZhuXing 
Yes..
I have checked multiple time and confirmed that this error is because of missing 'result' directory.

**Comment by JinZhuXing** [comment] 2020-09-11 13:50
@Ehtasha 
Thank you.

**Closed by JinZhuXing** 2020-09-11 13:50 UTC
Labels: question

**Comment by Muller-Liu** [comment] 2020-09-11 13:56
Thank both of you!
You are right, and that's how I figure it out.
Sorry to forget about this ...
At last, I really appreciate for your project helped me a lot @JinZhuXing !
